#!/usr/bin/env python3
"""Generates docker-compose.yml from config/targets.json."""

import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)

INTERNAL_PORT = 3000

# Laravel uses artisan serve which defaults to 8000; we override to 3000 via command
# All targets are expected to listen on INTERNAL_PORT inside the container

def healthcheck_path(target: dict) -> str:
    tests = target.get("tests", {})
    for test_name in ("holamundo",):
        if test_name in tests:
            return tests[test_name]["path"]
    # fallback: first test path
    if tests:
        return next(iter(tests.values()))["path"]
    return "/"


def generate_service(target: dict) -> str:
    name = target["name"]
    port = target["port"]
    hc_path = healthcheck_path(target)

    lines = [
        f"  {name}:",
        f"    build: ./targets/{name}",
        f"    ports:",
        f'      - "{port}:{INTERNAL_PORT}"',
        f"    deploy:",
        f"      resources:",
        f"        limits:",
        f'          cpus: "1"',
        f"          memory: 512m",
        f"    healthcheck:",
        f'      test: ["CMD", "curl", "-f", "http://localhost:{INTERNAL_PORT}{hc_path}"]',
        f"      interval: 5s",
        f"      timeout: 3s",
        f"      retries: 15",
        f"      start_period: 30s",
    ]
    return "\n".join(lines)


def main():
    targets_path = os.path.join(ROOT, "config", "targets.json")
    with open(targets_path) as f:
        targets = json.load(f)

    enabled = [t for t in targets if t.get("enabled", True)]

    services_block = "\n\n".join(generate_service(t) for t in enabled)

    compose = f"""# Generated by scripts/generate_compose.py — do not edit manually.
# To regenerate: python3 scripts/generate_compose.py

services:

{services_block}
"""

    out_path = os.path.join(ROOT, "docker-compose.yml")
    with open(out_path, "w") as f:
        f.write(compose)

    print(f"Generated {out_path} with {len(enabled)} services:")
    for t in enabled:
        print(f"  {t['name']:20s} → localhost:{t['port']}")


if __name__ == "__main__":
    main()
